# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField()),
                ('match_type', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('display', models.TextField()),
                ('prediction', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Match_Wrestler_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField()),
                ('lost', models.BooleanField()),
                ('draw', models.BooleanField()),
                ('prediction', models.BooleanField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='match_wrestler_results',
            name='wrestler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Wrestler'),
        ),
        migrations.AlterUniqueTogether(
            name='match_wrestler_results',
            unique_together=set([('match_id', 'wrestler_id')]),
        ),
    ]
